const list = [
    {
      id: 1,
      title: "15 Inch - Universal Steering Wheel Cover (Black)",
      brand:"by Auto Oprema Auto Parts",
      price: 299,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/860c95523ebd3618e64a451e7a1f35ce.webp",
      amount: 1,
    },
    {
      id: 2,
      title: "Engine Oil 5W-30 (3.5L) (Cool Maker Fully Synthetic Oil)",
      brand: "by Hella",
      price: 2298,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/b016753f8a60e7345c36a17dad82a916.webp",
      amount: 1,
    },
    {
      id: 3,
      title: "H4 NIGHTEYE 72W LED Headlight Bulb Cool White Light",
      brand: "by Auto Oprema Auto Parts",
      price: 1799,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/47b43ea8fe84fb631e4a6dd1d5c8ab4c.webp",
      amount: 1,
    },
    {
      id: 4,
      title: "Key Cover Black",
      brand: "by Auto Oprema Auto Parts",
      price: 299,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/0e3133229b34469d782c07cc1dd848fc.webp",
      amount: 1,
    },
    {
      id: 5,
      title: "Universal Car Floor Mats (Set of 4) - Black",
      brand: "by Auto Oprema Auto Parts",
      price: 599,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/46d1b04c3d5deba96d9fa947acc1c6ca.webp",
      amount: 1,
    },
    {
      id: 6,
      title: "Auto Grip XXL Mobile Holder",
      brand: "by Bergmann Auto Parts",
      price: 579,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/dbbe43ba423f798c2b8c1142660a7f18.webp",
      amount: 1,
    },
    {
      id: 7,
      title: "Silver Car Body Cover ",
      brand: "by Auto Oprema Auto Parts",
      price: 693,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/00ab6d576e8a8f33d0df1352df7edf4e.webp",
      amount: 1,
    },
    {
      id: 8,
      title: "Car Duster",
      brand: "by JOPASU  Auto Parts  ",
      price: 699,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/995fd411fad7dd81afc5fea158938d51.webp",
      amount: 1,
    },
    {
      id: 9,
      title: "Car Pillow Back Rest Premium Cushion Memory Foam - Beige (Set of 2) ",
      brand: "by Autocruze Auto Parts",
      price: 1149,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/a5f4ac016b2010133ad72bf31876a10a.webp",
      amount: 1,
    },
    {
      id: 10,
      title: "C3 Battery Charger",
      brand: "by BOSCH",
      price: 2799,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/bbaad169bff53a94f2d6373e3e93afeb.webp",
      amount: 1,
    },
    {
      id: 11,
      title: "Hybrid Solutions Ceramic Spray Coating (500ml)",
      brand: "by Turtle Wax",
      price: 1649,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/2b07936ead4b82d0032b8a47390a2fd6.webp",
      amount: 1,
    },
    {
      id: 12,
      title: "Wiper Blade Set (22'/16')",
      brand: "by BOSCH",
      price: 393,
      img: "https://boodmo.com/media/cache/part_zoom_horizontal/images/parts/af738f7f36bddf47e271da46fd963bca.webp",
      amount: 1,
    },
];

export default list;